name: Git diff Check

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]

jobs:
  Analyze:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
          show-progress: false

      - name: Run git diff check
        run: |
          git config --global core.whitespace cr-at-eol,tab-in-indent
          git diff --check HEAD^
